# http://gadfly.sourceforge.net/gadfly.html
create table depts (dept_id varchar, dept_name varchar)
insert into depts(dept_id, dept_name) values ('SAL', 'Sales')
insert into depts(dept_id, dept_name) values ('SER', 'Service')
create table emps (emp_id integer, emp_name varchar, emp_passwd varchar, emp_addresses varchar, emp_dept_id varchar, emp_active integer, emp_phone varchar, create_dt varchar, change_dt varchar)
insert into emps (emp_id, emp_name, emp_passwd, emp_addresses, emp_dept_id, emp_active, emp_phone, create_dt, change_dt) values ( 1, 'Hoffmann', 'Hoffmann', 'Mr', 'SAL', 1, '+49-(0)-30 / 209 127 8-2', '2006-01-01 12:00:00.000', '2006-01-01 12:00:00.000')
create table skills (skill_id integer, skill_name varchar)
insert into skills(skill_id, skill_name) values (1, 'Java')
insert into skills(skill_id, skill_name) values (2, 'Python')
insert into skills(skill_id, skill_name) values (3, 'HTML')
insert into skills(skill_id, skill_name) values (4, 'Acquisition')
insert into skills(skill_id, skill_name) values (5, 'Marketing')
create table skills2emps (skill_id integer, emp_id integer)
insert into skills2emps (skill_id, emp_id) values ( 4, 1)
insert into skills2emps (skill_id, emp_id) values ( 5, 1)