version: "3.7"
services:
  zms2-ubuntu:
    build: .
    image: zms2:ubuntu
    ports:
      - 8080:8080
      - 8081:8081

    environment:
      - PYTHONUNBUFFERED="1"
      - CONFIG_FILE="/home/zope/etc/zope.ini"
      - INSTANCE_HOME="/home/zope"
      - CLIENT_HOME="/home/zope"
      - PYTHON="/home/zope/venv/bin/python"
      - SOFTWARE_HOME="/home/zope/venv/bin"
    volumes:
      - ./bin/:/home/zope/bin/
      - ./etc/:/home/zope/etc/
      - ./Extensions/:/home/zope/Extensions/:rw
      - ./var/:/home/zope/var/:rw

    ### Override the default command from the dockerfile.
    # command: sleep infinity
    command: /home/zope/bin/runall
